---
abstract: 'The great new Animal!'
author:
  - 'Tobin Harding <me@tobin.cc>'
build_requires:
  Test::More: '0'
configure_requires:
  Module::Build: '0'
dynamic_config: 1
generated_by: 'Module::Build version 0.4214, CPAN::Meta::Converter version 2.150001'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Animal
provides:
  Animal:
    file: lib/Animal.pm
    version: '0.01'
resources:
  license: http://opensource.org/licenses/artistic-license-2.0.php
version: '0.01'
