{ STAT_OK, "success" },
{ STAT_OK_ATTRIGN, "OK; some attrs ignored" },
{ STAT_OK_ATTRCON, "OK; some attrs conflicted" },
{ STAT_CLI_BADREQ, "invalid client request" },
{ STAT_CLI_FORBID, "request is forbidden" },
{ STAT_CLI_NOAUTH, "authentication required" },
{ STAT_CLI_NOPERM, "client not authorized" },
{ STAT_CLI_NOTPOS, "request not possible" },
{ STAT_CLI_TIMOUT, "client too slow" },
{ STAT_CLI_NOTFND, "no object found for URI" },
{ STAT_CLI_OBJGONE, "object no longer available" },
{ STAT_CLI_TOOBIG, "requested entity too big" },
{ STAT_CLI_TOOLNG, "attribute value too large" },
{ STAT_CLI_BADFMT, "unsupported doc format" },
{ STAT_CLI_NOTSUP, "attributes not supported" },
{ STAT_CLI_NOSCHM, "URI scheme not supported" },
{ STAT_CLI_NOCHAR, "charset not supported" },
{ STAT_CLI_ATTRCON,"attributes conflicted" },
{ STAT_CLI_NOCOMP, "compression not supported" },
{ STAT_CLI_COMPERR, "data can't be decompressed" },
{ STAT_CLI_FMTERR, "document format error" },
{ STAT_CLI_ACCERR, "error accessing data" },
{ STAT_SRV_INTERN, "unexpected internal error" },
{ STAT_SRV_NOTSUP, "operation not supported" },
{ STAT_SRV_UNAVAIL,"service unavailable" },
{ STAT_SRV_BADVER, "version not supported" },
{ STAT_SRV_DEVERR, "device error" },
{ STAT_SRV_TMPERR, "temporary error" },
{ STAT_SRV_REJECT, "server not accepting jobs" },
{ STAT_SRV_TOOBUSY, "server too busy" },
{ STAT_SRV_CANCEL, "job has been canceled" },
{ STAT_SRV_NOMULTI, "multi-doc jobs unsupported" },
