[package]
name = "hello"
version = "0.1.0"
authors = ["tcharding <me@tobin.cc>"]
edition = "2018"

[dependencies]
hello_macro = { path = "../hello_macro" }
hello_macro_derive = { path = "../hello_macro/hello_macro_derive" }
